def count(myBases):
        (count,acount,ccount,gcount,tcount) = (0,0,0,0,0)
        for i in myBases:
                count = len(myBases) 
                if i.upper() == "C":
                        ccount += 1.0 
                elif i.upper() == "G":
                        gcount += 1.0 
                else:
                        pass
        GCpercent = ((gcount + ccount) / count)*100    
        return GCpercent, count

print count("AGGCACAGTATACATACGACACAAGCAGATATTAAAGCGGACATGATGCAGCGGGTGCGGCAAATAAATCGGTACCTGCAAGACTATGGACCAAGCGTGCATATTGCGCAGTGAGTTACACCACAAGAGGTGGGTCCGCTTTGGTGAGAGATAATCCCGAAGACCAGAGCACTGCCCTTTTCATATCAACTGACCGCGTATACGTACGGGGCGGACCGTTTCCACTTCCAGCACAATTAGATCGCCTACGTAAAAGAGTATTGCGCACGGGTTCTGTGCTTCTTTAATACTTTGTGGATGAAGCTGTTGGTCTCATTAAGCAGAGATTGACTACGCGTTCGGGCGCAGATGTACGATAACCAACCCCGGCTGCAAACGGGAGATAGTCGTGGGGCCGCCACTAACGTCGGAGAGCTACCCGCGGCGATTTCATGGCTTATACATAGGGCATTGAAACGCGGACACACTTAGAGCCAAACACGGGCATCGTCAACATTGTCACAAAGACGCTGTTATGATCGTAATGCCTCAGGAACCCACACCAAGAGAGAATGATCCTTGCCCAAGCCCGGACTCATATTGAGTCTGGTAACTTCGTCCTAGAGTCTCAGTCTCACCCGGCCGACGCTATGGATGCGCATGGGGGCCATGCGGGAAAATCCATGACCCTGCCACCCCTACTGAGGACAGGTGTTTGGAAAGGACGATCTGAGTTTGGTGCTGTCGTACCCTCTCCGCGCAATCGTGTTGAGTGCTAGTCATGAGTAATGCCCAGACCAAGGGATCGACACGAATGTCACCCGGCATGGTATTTATCCTGTCTGCTCCTGGTTCACGGGCAACTCCC")
