sample = "TTCCCCTGTGTAAACAACCCGGGTTATGGGCCAGCGTTAAAGGTACGTTGCCTTCTAACTGTGACAAGGCCTTCAAGGTAATAAACGGGGGTAGAGCAGAGTAGTTGTAATGCCCGGGGCATAAAGTTTGGTCCGTTGTTTTCGCTCACCGGCGCGGCGAACCATGCTATTAGGGGTCAGAATTCGGGGTACGCCGTCATTGACCTCCTGTAGACTCACCGCTTAAATGCAAGATAAGAGAAACACGTCCCCCGCGTGCAATTACTTGGATCGCGTAGCACGCCACGGAGGTATGTGGACGGCTGCAATCGCACTTTTTGCAAAACCATCCATAAGGCTGGAATTATGCTGGCGGAAATCTTATGAAGGTTGCACTACGTATTTTACCACGGTGGGCTCCCAGCTTATCTTGTGAATCATCTCTGCGTTTCTCAGATGTATGAGCCACCGTAGATGTGTGAAATCCTTTAACTCTCGCAATATAGATGGCCGGTTACGAATATTTACACAACGAGTATCCCAAATGCAACCGTGCTAACCTCATTCAGTTAGTGGCGCACTGTGTAACTTGCACCGATCCAGTAGTCCCATAATATTAATATATGGTTGTCCGTCCCAGTGGGTTAGGAGGCGGCTATCACAGCGCACGGCGTCTTCGGTCCAGGTGTATATATAAATCAAGCGTGACTGATCTAACTGCTGACACCCTTTGAAGTCGCGTTTAGCCAGCGACAGGAGCTTTCACCCAGTAGTTACACGCATGACCGATCGCGGTGAACTACTTACCTCATTTCACGCCCGATTTGGCGTCTGCGATTAATATAATATTGCGCCTGTGGGGGGTAGAACATTCTCGTAGTTACATGCGGGCAGCATCAGAGATACCATTGTGTGAGTCCACTACGTTTAATTTTTTGGCCGTCCA"

RNA = []

'''for i in range(len(sample)):
	if sample[i] == "A":
		RNA.append("T")
	elif sample[i] == "C":
		RNA.append("G")
	elif sample[i] == "G":
		RNA.append("C")
	elif sample[i] == "T":
		RNA.append("U")
	else:
		RNA.append("X")
		print "Position %d not recognized" % i'''

for i in range(len(sample)):
	if sample[i] == "T":
		RNA.append("U")
	else:
		RNA.append(sample[i])

RNAfin = "".join(RNA)
print RNAfin
